### ISSUE TITLE
Pass Keybase Service STDERR Back Through API Errors

### ISSUE THREAD

**Issue by thebearjew** [keybase/keybase-chat-bot#32]
If a user is currently logged in to the keybase service, and attempts to initialize the bot, they will only get the exit code and stacktrace from `keybase-chat-bot`.

Example:

```sh
# Assuming paperkey is magically passed in
$ KB_USERNAME='jacobyoung' node demo/hello_world.js

Error: exited with code 2
    at ChildProcess.eval (webpack-internal:///1:521:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
```

Might be worth digging into the client code, but it seems like the following situations cause the service to exit with return code != 0

- Missing paperkey via `--paperkey` when specified
- Invalid paperkey
- User is already logged in when calling `oneshot`

Until we have better tests, nice workout would be to pipe the `STDERR` from `keybase oneshot` back through this module and present it on `STDERR` as well.

**Comment by malgorithms** [comment]
agree this would be a big plus.
